# Generated by Django 6.1.1 on 2026-10-07 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_worker_worker_company'),
        ('company_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workeruser',
            name='owned_company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company_app.company'),
        ),
    ]
