# Generated by Django 6.1.1 on 2026-10-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_workeruser_owned_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='workeruser',
            name='nationality',
            field=models.TextField(blank=True, max_length=25, null=True),
        ),
    ]
