# Generated by Django 6.1.1 on 2026-09-18 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_of_product', models.TextField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('product', models.TextField(blank=True, max_length=65, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.TextField()),
                ('date_of_creation', models.DateField()),
                ('volume_of_prodiction', models.TextField()),
                ('work_hours', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PhotoCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.ImageField(upload_to='')),
                ('compressed', models.ImageField(upload_to='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_app.company')),
            ],
        ),
    ]
